import dotenv from "dotenv";
dotenv.config();

export const kommoClients = {
  winsurf: {
    // 🔐 Credenciales (desde .env)
    KOMMO_LONG_TOKEN: process.env.CLIENTE1_KOMMO_LONG_TOKEN,
    SUBDOMAIN_KOMMO: process.env.CLIENTE1_SUBDOMAIN,

    OPENAI_API_KEY: process.env.CLIENTE1_OPENAI_API_KEY,

    DOTA_DOMAIN: process.env.CLIENTE1_DOTA_DOMAIN,
    DOTA_USER: process.env.CLIENTE1_DOTA_USER,
    DOTA_PASS: process.env.CLIENTE1_DOTA_PASS,

    DISCORD_WEBHOOK: process.env.CLIENTE1_DISCORD_WEBHOOK,

    // 🔢 IDs internos Kommo (NO sensibles)
    KOMMO_FIELD_ID_MENSAJEENVIAR: 3085880,
    KOMMO_FIELD_ID_CLAVE: 3088830,

    // 🤖 Salesbot (IDs)
    KOMMO_SALESBOT_RESPUESTA: 28988,
    KOMMO_SALESBOT_ID_COMUNIDAD: 29306,
    KOMMO_SALESBOT_ID_CBU: 29310,
    KOMMO_SALESBOT_ID_RECOMENDAR: 29344,
    KOMMO_SALESBOT_ID_SOPORTE: 29626,
    KOMMO_SALESBOT_ID_RETIRAR: 29840,
    KOMMO_SALESBOT_ID_RECOMENDE: 29842,
    KOMMO_SALESBOT_ID_GRATIS: 29844,
    KOMMO_SALESBOT_ID_SORTEO: 29846,
    KOMMO_SALESBOT_ID_LINK: 29848,
    KOMMO_SALESBOT_ID_WAGER: 29850,
    KOMMO_SALESBOT_ID_TRANSFIRIO: 29852,
    KOMMO_SALESBOT_ID_PRIMERCBU: 29870,

    HORAS_100: [0, 10, 15],
    DOTA_USER_SUFFIX: "Dota"
  }
};