import dotenv from "dotenv";
dotenv.config();

export const kommoClients = {
  winsurf: {
    // 🔐 Credenciales (desde .env)
    KOMMO_LONG_TOKEN: process.env.CLIENTE1_KOMMO_LONG_TOKEN,
    SUBDOMAIN_KOMMO: process.env.CLIENTE1_SUBDOMAIN,

    OPENAI_API_KEY: process.env.CLIENTE1_OPENAI_API_KEY,

    DOTA_DOMAIN: process.env.CLIENTE1_DOTA_DOMAIN,
    DOTA_USER: process.env.CLIENTE1_DOTA_USER,
    DOTA_PASS: process.env.CLIENTE1_DOTA_PASS,

    DISCORD_WEBHOOK: process.env.CLIENTE1_DISCORD_WEBHOOK,

    // 🔢 IDs internos Kommo
    KOMMO_FIELD_ID_MENSAJEENVIAR: 3085880,
    KOMMO_FIELD_ID_CLAVE: 3088830,

    // 🤖 Salesbot (IDs)
    KOMMO_SALESBOT_RESPUESTA: 28988,
    KOMMO_SALESBOT_ID_COMUNIDAD: 29306,
    KOMMO_SALESBOT_ID_CBU: 29310,
    KOMMO_SALESBOT_ID_RECOMENDAR: 29344,
    KOMMO_SALESBOT_ID_SOPORTE: 29626,
    KOMMO_SALESBOT_ID_RETIRAR: 29840,
    KOMMO_SALESBOT_ID_RECOMENDE: 29842,
    KOMMO_SALESBOT_ID_GRATIS: 29844,
    KOMMO_SALESBOT_ID_SORTEO: 29846,
    KOMMO_SALESBOT_ID_LINK: 29848,
    KOMMO_SALESBOT_ID_WAGER: 29850,
    KOMMO_SALESBOT_ID_TRANSFIRIO: 29852,
    KOMMO_SALESBOT_ID_PRIMERCBU: 29870,
    KOMMO_SALESBOT_ID_ELEGIR: 31196,
    KOMMO_SALESBOT_ID_CARGA_EXITOSA: 35100,
    KOMMO_SALESBOT_ID_TIRADAS_GRATIS: 43312,

    HORAS_100: [0, 20, 15],
    DOTA_USER_SUFFIX: "Ws"
  },
  crown: {
    // 🔐 Credenciales (desde .env)
    KOMMO_LONG_TOKEN: process.env.CLIENTE2_KOMMO_LONG_TOKEN,
    SUBDOMAIN_KOMMO: process.env.CLIENTE2_SUBDOMAIN,

    OPENAI_API_KEY: process.env.CLIENTE2_OPENAI_API_KEY,

    DOTA_DOMAIN: process.env.CLIENTE2_DOTA_DOMAIN,
    DOTA_USER: process.env.CLIENTE2_DOTA_USER,
    DOTA_PASS: process.env.CLIENTE2_DOTA_PASS,

    DISCORD_WEBHOOK: process.env.CLIENTE2_DISCORD_WEBHOOK,

    // 🔢 IDs internos Kommo
    KOMMO_FIELD_ID_MENSAJEENVIAR: 1393034,
    KOMMO_FIELD_ID_CLAVE: 1080828,

    // 🤖 Salesbot (IDs)
    KOMMO_SALESBOT_RESPUESTA: 103859,
    KOMMO_SALESBOT_ID_COMUNIDAD: 103831,
    KOMMO_SALESBOT_ID_CBU: 103829,
    KOMMO_SALESBOT_ID_RECOMENDAR: 103839,
    KOMMO_SALESBOT_ID_SOPORTE: 103845,
    KOMMO_SALESBOT_ID_RETIRAR: 103843,
    KOMMO_SALESBOT_ID_RECOMENDE: 103841,
    KOMMO_SALESBOT_ID_GRATIS: 103833,
    KOMMO_SALESBOT_ID_SORTEO: 103847,
    KOMMO_SALESBOT_ID_LINK: 103835,
    KOMMO_SALESBOT_ID_WAGER: 103851,
    KOMMO_SALESBOT_ID_TRANSFIRIO: 103849,
    KOMMO_SALESBOT_ID_PRIMERCBU: 103837,
    KOMMO_SALESBOT_ID_ELEGIR: 103897,
    KOMMO_SALESBOT_ID_CARGA_EXITOSA: 106693,
    KOMMO_SALESBOT_ID_TIRADAS_GRATIS: 106689,

    HORAS_100: [12, 18, 22],
    DOTA_USER_SUFFIX: "Dota"
  }
};