import dotenv from "dotenv";
dotenv.config();

export const kommoClients = {
  cliente1: {
    // 🔐 Credenciales (desde .env)
    KOMMO_LONG_TOKEN: process.env.CLIENTE1_KOMMO_LONG_TOKEN,
    SUBDOMAIN_KOMMO: process.env.CLIENTE1_SUBDOMAIN,

    OPENAI_API_KEY: process.env.CLIENTE1_OPENAI_API_KEY,

    DOTA_DOMAIN: process.env.CLIENTE1_DOTA_DOMAIN,
    DOTA_USER: process.env.CLIENTE1_DOTA_USER,
    DOTA_PASS: process.env.CLIENTE1_DOTA_PASS,

    DISCORD_WEBHOOK: process.env.CLIENTE1_DISCORD_WEBHOOK,

    // 🔢 IDs internos Kommo (NO sensibles)
    KOMMO_FIELD_ID_MENSAJEENVIAR: 3085880,
    KOMMO_FIELD_ID_CLAVE: 3088830,

    KOMMO_SALESBOT_RESPUESTA: 1001,
    KOMMO_SALESBOT_ID_COMUNIDAD: 1002,
    KOMMO_SALESBOT_ID_CBU: 1003,
    KOMMO_SALESBOT_ID_RECOMENDAR: 1004,
    KOMMO_SALESBOT_ID_RECOMENDE: 1005,
    KOMMO_SALESBOT_ID_SOPORTE: 1006,
    KOMMO_SALESBOT_ID_RETIRAR: 1007,
    KOMMO_SALESBOT_ID_GRATIS: 1008,
    KOMMO_SALESBOT_ID_SORTEO: 1009,
    KOMMO_SALESBOT_ID_LINK: 1010,
    KOMMO_SALESBOT_ID_WAGER: 1011,
    KOMMO_SALESBOT_ID_TRANSFIRIO: 1012,
    KOMMO_SALESBOT_ID_PRIMERCBU: 1013,

    HORAS_100: [0, 10, 15],
    DOTA_USER_SUFFIX: "Dota"
  }
};